---
title: "rs-ws-03-2"
author: "keltoskytoi, Jana Schnemann, Sebastian Richter"
date: "17 November 2016"
output: html_document
---

```
```

## Our strategy: 

*Load the two aerial images which shall be compared*
*Extract those cell values of the line of cell in one raster which is closest to the other raster to a data frame*
*Compare the two data frames, i.e. by substracting them from each other*
*The result is an indication for how much the radiometric alignment differs between the two aerial images*

创
library(raster)
setwd("C:/Users/Keltoskytoi/Desktop/WS2016_2017/msc-phygeo-class-of-2016-keltoskytoi/remote_sensing")

s1=stack("474000_5630000.tif")
s2=stack("474000_5632000.tif")
创
##  Step 1:  Raster in data.frame

创
s1.data.frame=as.data.frame(s1, optional = FALSE)
s2.data.frame=as.data.frame(s2, optional = FALSE)
创

## Step 2:  s1: Reihe 10000 und Spalten 1-10000 s2: Reihe 1 und Spalten 1-10000

创
row.values.1=s1.data.frame[c(99990001:100000000),]
row.values.2=s2.data.frame[c(1:10000), ]
创

## zur Visualisierung:
## nrow(s1.data.frame)
## ncol(s1.data.frame)
## head(s1.data.frame)
## nrow(s2.data.frame)
## ncol(s2.data.frame)
## head(s2.data.frame)


## Step 3:  Werte der beiden variablen row.values.1 und row.values.2 vergleichen
