---
title: "da-ws-08-1"
author: "keltoskytoi, Jana Schönemann, Sebastian Richter"
date: "19 Dezember 2016"
output: html_document
---
## Read table, librarys and making preparations 
```{r eval=FALSE}
holz <- read.table ("C:/Users/Keltoskytoi/Desktop/data/data_analysis/csv/hessen_holzeinschlag_1997-2014_clean.csv.csv", header = TRUE, sep = ";", dec = ",")
holz <- holz [-19,]

library (mgcv)
library(car)

dep <- holz$Buche
ind <- holz$Eiche
```
## Double-looping around
```{r eval=FALSE}
ergebnis <- lapply (seq (3:13), function (k){
  
  modell <- lapply(seq(100), function (i){
    set.seed(i)
    s <- sample (nrow(holz), nrow(holz)*0.8)
    train <- holz[s,]
    test <- holz[-s,]
    obs <- test$Buche
    gamobs <- gam(Buche ~ s(Eiche, k = k, fx = TRUE), data = train)
    gampred <- predict(gamobs, newdata=test)
    return(data.frame(RMSE = sqrt(mean((gampred-obs)^2)),
                      Adj_R_sqrd = summary(gamobs)$r.sq))
  })
  modell <- do.call ("rbind", modell)
  RMSE <- modell$RMSE/max(modell$RMSE)
  return(data.frame (Knoten = k,
                     mean_Adj_R_sqrd = mean(modell$Adj_R_sqrd),
                     mean_RMSE = mean(RMSE),
                     RMSE_max = mean(RMSE)+sd(RMSE),
                     RMSE_min = mean(RMSE)-sd(RMSE)))
})

ergebnis <- do.call("rbind", ergebnis)
``` 
## Plotting
```{r eval=FALSE}
knots <- seq(3:13)
y <- c(ergebnis$mean_Adj_R_sqrd, ergebnis$mean_RMSE, ergebnis$RMSE_max, ergebnis$RMSE_min)

matplot (knots, y, type ="l")
plot(knots, y, type ="l",
     main ="Result of Cross-Validation",
     xlab = "Knots",
     ylab = " ")
colors <- rainbow(y)
linetype <- c(1:y)

# add lines
for (i in 2:5) {
  statistic <- subset(ergebnis, ncol= i)
  lines(knots, y, type="b", lwd=1.5,
        lty=linetype[i], col=colors[i], pch=plotchar[i])
}

# add lines
for (i in 1:ntrees) {
  tree <- subset(Orange, Tree==i)
  lines(tree$age, tree$circumference, type="b", lwd=1.5,
        lty=linetype[i], col=colors[i], pch=plotchar[i])
}

# add a title and subtitle
title("Tree Growth", "example of line plot")

# add a legend
legend(xrange[1], yrange[2], 1:ntrees, cex=0.8, col=colors,
       pch=plotchar, lty=linetype, title="Tree")


plot(knots, ergebnis$mean_Adj_R_sqrd, type ="l", col= "blue",
     main ="Result of Cross-Validation",
     xlab = "Knots",
     ylab = "")

legend(9, 0.7, paste("knots", knots, sep=" "), col = cols, lty=2, cex=0.75)

### short variation o visualisation: 

knots <- seq(3:13)
ergebnis <- ergebnis [,-1]

matplot (knots, ergebnis, type ="l", lty = 2:5, col=1:4,
         main ="Result of Cross-Validation",
         xlab = "knots",
         ylab = " ")

legend ("bottomright", paste("knots", knots, sep=" "), lty=2, cex=0.75)
```
