# Pfade setzen-----------------------------------------------------------------
source("C:/Users/Keltoskytoi/Desktop/data/data_analysis/fun/Source_da.R")

# libraries und function einlesen----------------------------------------------
library(zoo)
library(car)
install.packages("timeDate")
install.packages("forecast")

# Dateien einlesen-------------------------------------------------------------
dwd <- read.table(paste0(path_csv, "produkt_synop_Terminwerte_20060701_20151231_03164.txt"), header=TRUE, sep = ";")

#Schreibe neue Spalte mit Monaten in Tabelle dwd
dwd$AGG_J_M <- substr(dwd$MESS_DATUM, 1, 6)

#Summiere Niederschlagshöhe pro Monat
dwd_all <- aggregate(dwd$NIEDERSCHLAGSHOEHE, by = list(dwd$AGG_J_M), FUN = sum)

#Tabelle umbenennen, Datumsformat ändern
colnames(dwd_all) <- c("Date", "percipitation")
dwd$DATUM <- strptime(paste0(dwd$MESS_DATUM, "00"), format = "%Y%m%d%H%M")
head(dwd$DATUM)

#Train- und Testdatensatz bilden
train <- dwd_all [1:90, ] #train bis Dez.2013
test <- dwd_all [91:114, ] #test ab Jan.2014

#Generate time series data of class ts as needed for auto.arima function
tam_train <- ts(train$percipitation, start = c(2006, 7), end = c(2013, 12), frequency = 12)
tam_test <- ts(test$percipitation, start = c(2014, 1), end = c(2015, 12), frequency = 12)


##ARIMA
#Dataframe mit allen Kombinationen aus p,d,q,ps,ds,qs (mit Funktion expand.grid)
modit <- expand.grid(p = seq(0, 5), d = seq(0, 2), q = seq(0, 5), ps = seq(0, 2), ds = seq(0, 2), qs = seq(0, 2))

abc <- lapply(1:(nrow(modit)), function(i){
  comb <- modit[i,]
  armod <- try(arima(tam_train, order = c(comb[,1],comb[,2],comb[,3]),
                     seasonal = list(order = c(comb[,4],comb[,5],comb[,6]), period = NA),
                     method = "ML", kappa = 1e6))  # the order is p, d, q, ps, ds, qs
  if (class(armod) == "try-error") {
    return(NULL)
  } else {
    pred <- predict(armod, n.ahead = 24, newdata = tam_test)
    obsv <- tam_test
    rmse <- sqrt(mean((pred$pred - obsv)^2))
    return(data.frame(rmse,armod$aic,comb$p,comb$d,comb$q,comb$ps,comb$ds,comb$qs))
  }
})
abc <- do.call("rbind", abc)  # 2757 lines -> 159 outtakes from the 2916 modit lines, first was modit line 191
print(abc)
summary(abc)

## saveRDS(abc, file = "C:/Users/Keltoskytoi/Desktop/data/data_analysis/results/da-ws-10-1.rds")
abc <- readRDS(file = "C:/Users/Keltoskytoi/Desktop/data/data_analysis/results/da-ws-10-1.rds")

min(abc$rmse)
rmse_min <- abc[min(abc$rmse), ]  # Why different than the real minimum?
print(rmse_min)  # p=2, d=1, q=1, ps=0, ds=0, qs=0

# predict monthly precipitation heights with optimal model
arimamod <- arima(tam_train, order = c(2,1,1),
                  seasonal = list(order = c(0,0,0), period = NA),
                  method = "ML", kappa = 1e6)  # the order is p, d, q, ps, ds, qs

plot(forecast(arimamod), ylim=c(0,140))
points(tam_test, col = "red")
lines(tam_test, col = "red")

# predict monthly precipitation heights with optimal model generated by auto.arima
autoarimamod <- auto.arima(tam_train, max.p = 5, max.q = 5, max.d = 2, max.P = 2, max.Q = 2, max.D = 2, stationary = TRUE, seasonal=TRUE)
summary(autoarimamod)

pred <- predict(autoarimamod, n.ahead = 24)
obsv <- tam_test
rmse <- sqrt(mean((pred$pred - obsv)^2))
print(rmse)

plot(forecast(autoarimamod), ylim=c(0,140))
points(tam_test, col = "red")
lines(tam_test, col = "red")

# The predicted precipitation of our model (rmse = 28.55518) appears to be slightly closer to the 
# observed precipitation than the predicted precipitation of the automatically retrieved model (rmse = 31.4242). 
# But the predicted precipitation of the automatically retrieved model looks to be more likely to happen 
# because of its seasonal variation.